"""empty message

Revision ID: e96b9f3b10cd
Revises: cce7138dedb4
Create Date: 2020-12-23 13:36:35.966148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96b9f3b10cd'
down_revision = 'cce7138dedb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'name')
    # ### end Alembic commands ###
